services:
  psql:
    image: postgres
    command: ["psql"]
    environment:
      PGPASSWORD: postgres
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
    volumes:
      - ./exercises:/exercises
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
      interval: 5s
      timeout: 5s
      retries: 5


